---
interval: 10s
alert_manager:
  url: http://localhost:9093/api/v1/alerts
  labels:
    service: my-great-webapp
watch:
  http:
    targets:
      - url: http://example.com/
      - url: http://example.cm/
  net:
    targets:
      - network: tcp
        address: example.com:80
      - network: tcp
        address: example.com:22

